### ISSUE TITLE
判断账号是否已注册接口

### ISSUE THREAD

**Issue by dustsky** [hardthings/Server#2]
判断账号是否存在，输入位数不全的手机号，或者字符串账号(是否限制只有手机号或者邮箱作为登录账号需讨论)，状态码也为200，提示msg 为操作成功。

期望：输入正确账号，返回200，提示操作成功。输入已注册手机号或者邮箱，提示消息：账号已注册。

**Comment by FrankBian** [comment]
首先我们得明确这个 输入的正确性验证 是放在前端 还是放在Server ~

**Comment by dustsky** [comment]
未注册的合法账号（gsmxsky@gmail.com），验证是否已注册，返回信息提示操作成功。状态码200.

期望：未注册的合法账号，返回信息提示“账号已注册”。

这个是否已经注册，应该是在服务端判断的。

**Comment by FrankBian** [comment]
已处理
