### ISSUE TITLE
关于返回值的一些调整

### ISSUE THREAD

**Issue by dustsky** [hardthings/Server#3]
1.msg 返回值调整为相关英文说明。
2.返回值如果是null，调整为一个空字符串。例如登录失败接口中的data字段返回null,可以调整为""；以后的接口也做类似处理。

**Comment by FrankBian** [comment]
我给你们的msg，你们是怎么用的？ 是要经过处理 还是直接显示给用户？


Best Regards,
Frank Bian

**Comment by FrankBian** [comment]
调整为“” 又是出于什么考虑?

**Comment by FrankBian** [comment]
没有充分考虑的话 不建议使用“” 代替 null作为返回值！

**Comment by dustsky** [comment]
第一个问题：不能用msg对应值直接显示，要在终端做处理再显示，如果终端语言选择的英文系统，若显示中文不伦不类了。第一个可以不调整，本地化用中文做键也可以做，我觉得用英文感觉更好些。
第二个问题：ios 这边跟后台交互时，遇到null程序会crash，要做一些判断才能处理，现在接口返回数据比较少，后期数据可能比较多，如果不规范，在终端这边有可能会对每个有可能是null的字段处理，处理量比较大。用空字符串或者nil，更安全些。这个调整后，觉得更加规范。

两个可以在终端调整解决，但是接口就不怎么规范了。

**Comment by FrankBian** [comment]
如果不是显示给用户的话，我这边统一成 英文msg没问题！

另一个，关于null的问题，从语义上来讲用null来表示 空数据是更合理的，因为可能存在结果为空字符串的情况！



Best Regards,
Frank Bian

**Comment by FrankBian** [comment]
你所说的遇到null会crash这是每个程序都会遇到的， 你将json结果 parse成串之后，应该对data的类型进行判断！ 这才是规范的做法，而不是将parse出来的结果直接拿去用！

**Comment by dustsky** [comment]
你那边接口是返回可以统一处理，这个也是减少工作量，如果我知道后台不会返回null，那就没必要白加那么多废代码去一个一个判断了。统一处理比较方便，我这边是要一个一个接口去处理，都是处理，选个方便点的更好。

**Comment by dustsky** [comment]
做肯定没问题，选哪种方式才是最重要的。如果你那边统一没法规范，那就只有终端做了。

**Comment by FrankBian** [comment]
这与统一处理无关！！！ 不要把前后台的逻辑 耦合在一起！！！ 我Server这边统一的规范就是 空数据返回NULL

**Comment by FrankBian** [comment]
那就去做！


Best Regards,
Frank Bian

**Comment by dustsky** [comment]
关了吧。

**Comment by dustsky** [comment]
忘记了，把第一个改了，再关。

**Comment by FrankBian** [comment]
你个逗比 ~

**Comment by FrankBian** [comment]
我关就行了
